include:
  - ss10.md
  - pc11.md
  - ss10/govt.md
  - ss10/wwi.md
  - ss10/int.md
  - ss10/wwii.md
  - ss10/cold.md
  - ss10/can.md
  - pc11/quad.md
  - pc11/quad/func.md
  - pc11/quad/equ.md
  - pc11/quad/apply.md
  - pc11/ratio.md
  - pc11/radi.md
  - pc11/trig.md
