blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/HyperionU/Nota-Set/discussions
    about: Please ask and answer questions here.
  - name: Security Reports
    url: https://github.com/HyperionU/Nota-Set/security/advisories
    about: Please report security vulnerabilities here.
    
